name: "DevOps Metrics from GitHub"
author: 'Sten Otto Johnsen'
description: 'Outputs a set of key metrics based on GitHub issues and releases'
branding:
  icon: "align-justify"
  color: "green"
inputs:
  owner:  # organisation
    description: 'Owner of the repo. Org or user'
    required: false
  repo:  # repository
    description: 'Repository name'
    required: false
  token:  # repository
    description: 'Repository access token'
    required: false
outputs:
  deploy-rate: # pull requests merged to main per week
    description: 'Deployment rate'

  lead-time: # Average time between first commit on a feature and its deployment into production
    description: 'Feature lead-time'

  change-failure-rate: # Percentage of releases causing an Issue tagged with "bug"
    description: 'Change failure rate'

  mttr: # Average time between releases where "bug" is created and closed
    description: 'Mean time to restore'

runs:
  using: 'node16'
  main: 'dist/index.js'
