---
rules:
  impostor-commit:
    ignore:
      - badges.yaml
      - ci.yml
      - codeql-analysis.yml
      - dora.yaml
      - linter.yml
      - release-please.yml
      - stryker.yaml
      - test.yml
  template-injection:
    ignore:
      - badges.yaml
      - ci.yml
      - dora.yaml
      - release-please.yml
      - stryker.yaml
      - test.yml
  cache-poisoning:
    ignore:
      - test.yml
