name: Create Badge on DevOps Metrics

on: 
  push:
  schedule:
  - cron: '30 0 * * *'

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    name: Checking the dora metrics
    steps:
      - name: DevOps Metrics from GitHub
        uses: stenjo/devops-metrics-action@v0.3.1-beta
        id: dora
        with:
          owner: 'stenjo'
          repo: 'devops-metrics-action'
          token: ${{ secrets.GITHUB_TOKEN }}

      # Use the output from the `dora` step
      - name: Get the output rate
        run: echo "The deploy rate was ${{ steps.dora.outputs.deploy-rate }}"      # Use the output from the `dora` step
      - name: Get the change failure rate
        run: echo "The change failure rate was ${{ steps.dora.outputs.change-failure-rate }}"
      - name: Get the mean time to restore
        run: echo "The mean time to restore was ${{ steps.dora.outputs.mttr }}"

      - name: Create the Badge
        uses: Schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_AUTH_TOKEN }}
          gistID: ebb0efc5ab5afb32eae4d0cdc60d563a
          filename: deploy-rate.json
          label: Deploy Rate
          message: ${{ steps.dora.outputs.deploy-rate }}
          valColorRange: ${{ steps.dora.outputs.deploy-rate }}
          maxColorRange: 7
          minColorRange: 1
          invertColorRange: true
          # color: ${{ steps.dora.outputs.color }}
          # namedLogo: 
