on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4
        id: release
        with:
          release-type: simple
          package-name: release-please-action

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: tag major and minor versions
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STEPS_RELEASE_OUTPUTS_MAJOR: ${{ steps.release.outputs.major }}
          STEPS_RELEASE_OUTPUTS_MINOR: ${{ steps.release.outputs.minor }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git tag -d v${STEPS_RELEASE_OUTPUTS_MAJOR} || true
          git tag -d v${STEPS_RELEASE_OUTPUTS_MAJOR}.${STEPS_RELEASE_OUTPUTS_MINOR} || true
          git push origin :v${STEPS_RELEASE_OUTPUTS_MAJOR} || true
          git push origin :v${STEPS_RELEASE_OUTPUTS_MAJOR}.${STEPS_RELEASE_OUTPUTS_MINOR} || true
          git tag -a v${STEPS_RELEASE_OUTPUTS_MAJOR} -m "Release v${STEPS_RELEASE_OUTPUTS_MAJOR}"
          git tag -a v${STEPS_RELEASE_OUTPUTS_MAJOR}.${STEPS_RELEASE_OUTPUTS_MINOR} -m "Release v${STEPS_RELEASE_OUTPUTS_MAJOR}.${STEPS_RELEASE_OUTPUTS_MINOR}"
          git push origin v${STEPS_RELEASE_OUTPUTS_MAJOR}
          git push origin v${STEPS_RELEASE_OUTPUTS_MAJOR}.${STEPS_RELEASE_OUTPUTS_MINOR}
