name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - name: Run tests
      run: |
        npx jest --coverage | tee ./coverage.txt && exit ${PIPESTATUS[0]}

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v7
      
    - name: Jest Coverage Comment
      id: coverageComment
      uses: MishaKav/jest-coverage-comment@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        summary-title: Jest Coverage (summary)
        title: Test Coverage
        coverage-summary-path: coverage/coverage-summary.json
        coverage-path: ./coverage.txt

    - name: Check the output coverage
      run: |
        echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
        echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
        echo "Summary HTML - ${{ steps.coverageComment.outputs.summaryHtml }}"

    - name: Create the Badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      if: steps.branch-name.outputs.current_branch == 'main'
      with:
        auth: ${{ secrets.GIST_AUTH_TOKEN }}
        gistID: 9ce1ad7d8e9db99796e782b244eefa4a
        filename: devops_metrics__${{ steps.branch-name.outputs.current_branch }}.json
        label: Test Coverage
        message: ${{ steps.coverageComment.outputs.coverage }}%
        color: ${{ steps.coverageComment.outputs.color }}
        namedLogo: jest


  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - uses: ./
      with:
        owner: stenjo
        repo: '[dora,Middager]'
        token: ${{ secrets.GITHUB_TOKEN }}
